eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET}

logging.level.root=WARN
logging.level.org.springframework.cloud.gateway=INFO

spring.cloud.gateway.default-filters[0].name=Retry
spring.cloud.gateway.default-filters[0].args.retries=2
spring.cloud.gateway.default-filters[0].args.statuses=SERVICE_UNAVAILABLE
spring.cloud.gateway.default-filters[0].args.methods=GET,POST