spring.application.name=api-gateway

server.port=8090

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# We define routes manually
spring.cloud.gateway.discovery.locator.enabled=false

# ===========================
# AUTH
# ===========================
spring.cloud.gateway.routes[0].id=auth-route
spring.cloud.gateway.routes[0].uri=lb://securebank-api
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# ===========================
# ACCOUNT
# ===========================
spring.cloud.gateway.routes[1].id=account-route
spring.cloud.gateway.routes[1].uri=lb://account-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/accounts/**,/api/v1/admin/accounts/**

# ===========================
# LOAN
# ===========================
spring.cloud.gateway.routes[2].id=loan-route
spring.cloud.gateway.routes[2].uri=lb://loan-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/loans/**,/api/v1/admin/loans/**

# ===========================
# NOTIFICATION
# ===========================
spring.cloud.gateway.routes[3].id=notification-route
spring.cloud.gateway.routes[3].uri=lb://notification-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/notifications/**

# ===========================
# KYC
# ===========================
spring.cloud.gateway.routes[4].id=kyc-route
spring.cloud.gateway.routes[4].uri=lb://securebank-api
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/kyc/**,/api/v1/teller/kyc/**

# ===========================
# TRANSACTIONS
# ===========================
spring.cloud.gateway.routes[5].id=transaction-route
spring.cloud.gateway.routes[5].uri=lb://securebank-api
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/transactions/**

# ===========================
# CARDS
# ===========================
spring.cloud.gateway.routes[6].id=card-route
spring.cloud.gateway.routes[6].uri=lb://securebank-api
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/cards/**

# ===========================
# ACCOUNT SECURITY
# ===========================
spring.cloud.gateway.routes[7].id=account-security-route
spring.cloud.gateway.routes[7].uri=lb://securebank-api
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/account-security/**

# ===========================
# GENERIC ADMIN
# ===========================
spring.cloud.gateway.routes[8].id=admin-route
spring.cloud.gateway.routes[8].uri=lb://securebank-api
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/admin/**

# ===========================
# ACTUATOR
# ===========================
spring.cloud.gateway.routes[9].id=actuator-route
spring.cloud.gateway.routes[9].uri=lb://securebank-api
spring.cloud.gateway.routes[9].predicates[0]=Path=/actuator/**

jwt.secret=${JWT_SECRET:MySecureBankJwtSecretKey2026VerySecure123456789}

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always