eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET}

logging.level.root=WARN
logging.level.org.springframework.cloud.gateway=INFO