spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

logging.level.root=WARN
logging.level.com.ehtesham.loan=INFO